package com.huang.model;

import java.util.List;

import com.huang.model.base.BaseUser;
import com.jfinal.kit.StrKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	public List<User> findAll() {
    	return dao.findAll();
    }

    public User findByUserName(String username) {
    	if (StrKit.isBlank(username))
		    return null;
		String sql = "select * from user where username = ?";
		return dao.findFirst(sql, username);
    }
}
